{{- if .Values.namespaces.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.core }}
  labels:
    {{- include "flexstack.labels" . | nindent 4 }}
    flexstack.io/profile: core
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.observability }}
  labels:
    {{- include "flexstack.labels" . | nindent 4 }}
    flexstack.io/profile: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.ai }}
  labels:
    {{- include "flexstack.labels" . | nindent 4 }}
    flexstack.io/profile: ai
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.identity }}
  labels:
    {{- include "flexstack.labels" . | nindent 4 }}
    flexstack.io/profile: identity
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.edge }}
  labels:
    {{- include "flexstack.labels" . | nindent 4 }}
    flexstack.io/profile: edge
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.messaging }}
  labels:
    {{- include "flexstack.labels" . | nindent 4 }}
    flexstack.io/profile: messaging
{{- end }}
