apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts

resources:
  - argo-rollouts.yaml

commonLabels:
  app.kubernetes.io/part-of: flexstack
  app.kubernetes.io/component: delivery
