# Messaging Services Kustomization
# Event bus and workflow orchestration
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: flexstack-messaging

namespace: flexstack-messaging

commonLabels:
  app.kubernetes.io/part-of: flexstack
  app.kubernetes.io/managed-by: kustomize
  flexstack.io/profile: messaging

resources:
  - nats.yaml
  - temporal.yaml
